# Generated by Django 2.2.5 on 2019-10-30 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDePago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmado', models.BooleanField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('entregado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=20)),
                ('telefono', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maxproductos.Usuario')),
            ],
            bases=('maxproductos.usuario',),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maxproductos.Usuario')),
            ],
            bases=('maxproductos.usuario',),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maxproductos.Usuario')),
                ('descripcionNegocio', models.CharField(max_length=200)),
                ('calificacion', models.IntegerField(default=0)),
            ],
            bases=('maxproductos.usuario',),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pedidos', models.ManyToManyField(to='maxproductos.Pedido')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxproductos.TipoProducto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxproductos.Proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxproductos.Cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxproductos.Proveedor'),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horaInicio', models.IntegerField()),
                ('horaFinal', models.IntegerField()),
                ('dia', models.CharField(max_length=15)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maxproductos.Proveedor')),
            ],
        ),
    ]
