# Generated by Django 2.2.5 on 2019-10-15 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maxproductos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='carro',
        ),
    ]
