# Generated by Django 2.2.5 on 2019-10-30 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxproductos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='maxproductos.Producto'),
        ),
    ]
