# Generated by Django 2.2.5 on 2019-11-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxproductos', '0002_auto_20191030_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horaFinal',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaInicio',
            field=models.TimeField(),
        ),
    ]
