# Generated by Django 2.2.5 on 2019-10-15 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxproductos', '0002_remove_producto_carro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maxproductos.Pedido'),
        ),
    ]
