# Generated by Django 2.2.5 on 2019-10-15 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maxproductos', '0003_auto_20191015_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maxproductos.Pedido'),
        ),
    ]
